export enum ORDER_STATE {
  DOLAPTA = 0,
  YERLESTIRILDI = 129,
  YERLESTIRILECEK = 128,
  TESLIM_EDILDI = 2,
  TESLIM_EDILECEK = 1,
  IADE_ALINDI = 4,
  IADE_ALINACAK = 64,
  MUSTERI_IADESI_ALINACAK = 512,
  MUSTERI_IADESI_ALINDI = 1024,
  SIPARIS_IPTAL = 256,
  SATICI_SIPARISI_ALINACAK = 2048,
  SATICI_SIPARISI_ALINDI = 4096,
  KAYIP = 8,


  HASARLI = 16,
  FRAUD = 32,
}
