export class UsersTable {
  public static users: any = [
    {
      userID: 1,
      userName: 'caner.can',
      password: 'senkron',
      fullName: 'Caner CAN',
      firstName: 'Caner',
      lastName: 'CAN',
      currencyISO: 'TRY',
      email: 'caner.can@senkron.net',
      image: './assets/avatars/150-3.jpeg',
      phone: '5444339877',
      accessToken: '8f3ae836da744329a6f93bf20594b5cc',
      refreshToken: 'f8c137a2c98743f48b643e71161d90aa',
      userTypeID: 2, // Manager
      occupation: 'Manager',
      companyName: 'Senkronthemes',
      language: `trTR`,
      job: 'Frontend Developer',
      timeZone: 'International Date Line West',
      website: 'https://senkron.net',
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromSenkronthemes: {
          newsAboutSenkronthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfSenkron: false,
          thingsYouMissedSindeYouLastLoggedIntoSenkron: true,
          newsAboutSenkronOnPartnerProductsAndOtherServices: true,
          tipsOnSenkronBusinessProducts: true,
        },
      },
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: 'L-12-20 Vertex, Cybersquare',
        city: 'Istanbul',
        state: 'Beylikdüzü',
        postCode: '34500',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/admin',
        facebook: 'https://facebook.com/admin',
        twitter: 'https://twitter.com/admin',
        instagram: 'https://instagram.com/admin',
      },
    },
    {
      userID: 2,
      userName: 'user',
      password: 'senkron',
      fullName: 'Patrick Lehner',
      firstName: 'Patrick',
      lastName: 'Lehner',
      currencyISO: 'EUR',
      email: 'user@senkron.net',
      image: './assets/avatars/150-2.jpg',
      phone: '5365437768',
      accessToken: '6829bba69dd3421d8762-991e9e806dbf',
      refreshToken: 'f8e4c61a318e4d618b6c199ef96b9e55',
      userTypeID: 2, // User
      occupation: 'User',
      companyName: 'Senkronthemes',
      language: 'enUS',
      job: 'Backend Developer',
      timeZone: 'International Date Line West',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromSenkronthemes: {
          newsAboutSenkronthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfSenkron: false,
          thingsYouMissedSindeYouLastLoggedIntoSenkron: true,
          newsAboutSenkronOnPartnerProductsAndOtherServices: true,
          tipsOnSenkronBusinessProducts: true,
        },
      },
      address: {
        addressLine: '3487  Ingram Road',
        city: 'Greensboro',
        state: 'North Carolina',
        postCode: '27409',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/user',
        facebook: 'https://facebook.com/user',
        twitter: 'https://twitter.com/user',
        instagram: 'https://instagram.com/user',
      },
    },
    {
      userID: 3,
      userName: 'admin',
      password: 'senkron',
      fullName: 'Sabrina Christiansen',
      firstName: 'Sabrina',
      lastName: 'Christiansen',
      currencyISO: 'USD',
      email: 'admin@senkron.net',
      image: './assets/avatars/150-1.jpg',
      phone: '5436577746',
      accessToken: 'd2dff7b82f784de584b60964abbe45b9',
      refreshToken: 'c999ccfe74aa40d0aa1a64c5e620c1a5',
      userTypeID: 1, // Admin
      occupation: 'Admin',
      companyName: 'Senkronthemes',
      language: 'enUS',
      job: 'UI/UX Designer',
      timeZone: 'International Date Line West',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      emailSettings: {
        emailNotification: true,
        sendCopyToPersonalEmail: false,
        activityRelatesEmail: {
          youHaveNewNotifications: false,
          youAreSentADirectMessage: false,
          someoneAddsYouAsAsAConnection: true,
          uponNewOrder: false,
          newMembershipApproval: false,
          memberRegistration: true,
        },
        updatesFromSenkronthemes: {
          newsAboutSenkronthemesProductsAndFeatureUpdates: false,
          tipsOnGettingMoreOutOfSenkron: false,
          thingsYouMissedSindeYouLastLoggedIntoSenkron: true,
          newsAboutSenkronOnPartnerProductsAndOtherServices: true,
          tipsOnSenkronBusinessProducts: true,
        },
      },
      address: {
        addressLine: '1467  Griffin Street',
        city: 'Phoenix',
        state: 'Arizona',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/guest',
        facebook: 'https://facebook.com/guest',
        twitter: 'https://twitter.com/guest',
        instagram: 'https://instagram.com/guest',
      },
    },
  ];

  public static tokens: any = [
    {
      id: 1,
      authToken: 'auth-token-' + Math.random(),
      refreshToken: 'auth-token-' + Math.random(),
    },
  ];
}
